version: "3.9"

services:
  search:
    image: searxng/searxng:latest
    networks:
     - reverse-proxy
    environment:
      - BASE_URL=https://search.actuary.dev
      - INSTANCE_NAME=search
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.search.rule=Host(`search.actuary.dev`)"
        - "traefik.http.routers.search.entrypoints=websecure"
        - "traefik.http.routers.search.service=search"
        - "traefik.http.routers.search.tls.certresolver=myresolver"
        - "traefik.http.services.search.loadbalancer.server.port=8080" 
        ## Middlewares
        - "traefik.http.routers.search.middlewares=authentik@file"
networks:
  reverse-proxy:
    external: true

